/** Every player-facing sentence, one entry each. English is the only language. */
const TEXT = {
  'label.food': 'Food',
  'label.production': 'Production',
  'label.military': 'Military',
  'label.money': 'Money',
  'label.science': 'Science',
  'label.culture': 'Culture',
  'label.population': 'Population',
  'label.health': 'Health',
  'label.damage': 'Damage',
  'label.range': 'Range',
  'label.move': 'Move',
  'reading.over': '{count}/{over}',
  'tooltip.food': 'The most basic need. Grows your population toward the growth threshold.',
  'tooltip.production': 'Materials of every sort. Build, improve, and shape the land.',
  'tooltip.military': 'A sad necessity. Defend and attack.',
  'tooltip.money': 'Exchange and opulence. Trade it for other goods, or amass it.',
  'tooltip.science':
    'The never-ending ingenuity of humanity. Draw, discard, and manipulate your cards.',
  'tooltip.culture': 'What the city creates and believes. Claims tiles, pushing the border out.',
  'tooltip.population':
    'Idle inhabitants, over all of them. Assign them to tiles, or turn them into units.',
  'tooltip.health': 'What the unit has left before it is killed.',
  'tooltip.damage': "The health this unit's attack removes.",
  'tooltip.range': 'The distance, in tiles, this unit attacks over.',
  'tooltip.move': 'The tiles this unit can still cross this turn, over its move.',
  'terrain.plain': 'Plain',
  'terrain.forest': 'Forest',
  'terrain.hills': 'Hills',
  'terrain.mountain': 'Mountain',
  'terrain.coast': 'Coast',
  'terrain.deep': 'Deep water',
  'terrain.urban': 'Urban',
  'panel.river': 'River',
  'feature.PH_Fertile': 'PH_Fertile',
  'improvement.PH_Mine': 'PH_Mine',
  'building.PH_City': 'PH_City',
  'building.PH_Farm': 'PH_Farm',
  'panel.no-yield': 'No yield',
  'button.turn': 'Turn {turn}',
  'button.end-turn': 'End turn',
  'button.city-mode': 'City mode',
  'kind.unit': 'Unit',
  'kind.building': 'Building',
  'kind.order': 'Order',
  'kind.action': 'Action',
  'unit.PH_Worker': 'PH_Worker',
  'unit.PH_Warrior': 'PH_Warrior',
  'card.PH_Worker': 'PH_Worker',
  'card.PH_Warrior': 'PH_Warrior',
  'card.PH_Farm': 'PH_Farm',
  'card.PH_March': 'PH_March',
  'card.PH_Harvest': 'PH_Harvest',
  'card.PH_Mine': 'PH_Mine',
  'card.PH_Urbanisation': 'PH_Urbanisation',
  'rules.PH_Worker': 'Turn an idle inhabitant into a worker',
  'rules.PH_Warrior': 'Turn an idle inhabitant into a warrior',
  'rules.PH_Farm': 'Build a farm',
  'rules.PH_March': "Refresh a unit's move points",
  'rules.PH_Harvest': 'Gain 2 food',
  'rules.PH_Mine': 'Improve hills with a mine',
  'rules.PH_Urbanisation': 'Terraform a plain into urban',
  'refusal.food': 'Costs {cost} food.',
  'refusal.production': 'Costs {cost} production.',
  'refusal.military': 'Costs {cost} military.',
  'refusal.money': 'Costs {cost} money.',
  'refusal.science': 'Costs {cost} science.',
  'refusal.culture': 'Costs {cost} culture.',
  'refusal.population': 'The city keeps its last inhabitant.',
  'refusal.idle': 'No idle population.',
  'refusal.city': 'A unit already stands on the city.',
  'refusal.tile': 'No tile to aim at.',
  'refusal.unit': 'No unit to refresh.',
  'browse.draw-pile': 'Draw pile — {count}',
  'browse.discard-pile': 'Discard pile — {count}',
  'menu.menu': 'Menu',
  'menu.settings': 'Settings',
  'menu.controls': 'Controls',
  'menu.new-chronicle': 'New chronicle',
  'control.pan-up': 'Pan up',
  'control.pan-left': 'Pan left',
  'control.pan-down': 'Pan down',
  'control.pan-right': 'Pan right',
  'control.zoom-in': 'Zoom in',
  'control.zoom-out': 'Zoom out',
  'control.city': 'City mode',
  'control.yields': 'Yield overlay',
  'control.inspect': 'Inspect',
  'control.back': 'Back',
  'controls.press': 'Press a key',
  'controls.empty': '—',
  'controls.default': 'Default',
  'key.arrow-up': '↑',
  'key.arrow-left': '←',
  'key.arrow-down': '↓',
  'key.arrow-right': '→',
  'key.space': 'Space',
  'key.mouse-1': 'Middle click',
  'key.mouse-3': 'Mouse 4',
  'key.mouse-4': 'Mouse 5',
  'key.wheel-up': 'Wheel up',
  'key.wheel-down': 'Wheel down',
  'defeat.title': 'Defeat',
  'defeat.capture': 'An enemy captured the city on turn {turn}.',
  'defeat.population': "The city's population reached zero on turn {turn}.",
} as const;

export type TextKey = keyof typeof TEXT;

export function text(key: TextKey, values: Record<string, number> = {}): string {
  return TEXT[key].replace(/\{(\w+)\}/g, (_, name: string) => String(values[name]));
}
